all: nuklearGLFWOpenGL3.so

nuklearGLFWOpenGL3.so: nuklear.h nuklear_glfw_gl3.h nuklearGLFWOpenGL3.c nuklearWrappers.h
	gcc -Wl,-undefined -Wl,dynamic_lookup -dynamiclib \
		$(shell pkg-config --cflags glfw3) $(shell pkg-config --libs glfw3)  \
		$(shell pkg-config --cflags glew) $(shell pkg-config --libs glew) \
		nuklearGLFWOpenGL3.c -o nuklearGLFWOpenGL3.so
